### ISSUE TITLE
Implement REPL show methods

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/ECharts.jl#12]
Use Blink, pop up HTML page?

**Comment by davidanthoff** [comment]
I have an early prototype of a Blink based display system that could be shared by multiple plotting libraries: https://github.com/davidanthoff/BlinkDisplay.jl/blob/master/src/BlinkDisplay.jl. The basic idea is that this package pushes a display onto the base display multimedia stack, and then supports viewing of various MIME types in a Blink window. The whole thing is kind of inspired by DevTools.jl, but would be more narrow.

The current version is pretty rough and needs a fair bit of love, so I'm not suggesting you rely on it right now, just wanted to alert you to it.

Plotting packages would just have to implement the various ``show`` methods for supported MIME types.

Given the trend with jupyterlab and nteract, I think the right strategy in general would be that there is a MIME type for ECharts that is directly support by BlinkDisplay.jl, so that we don't have to deal with all these issues of how to embed the javascript in something that is returned from a html show method.

**Comment by randyzwitch** [comment]
How does this differ from WebIO.jl (other than the fact WebIO never seems like it will be released on METADATA)

**Comment by davidanthoff** [comment]
I have no idea :) I'm not sure whether WebIO.jl hooks into the normal base display system or not... And as I said, I'm not sure whether I will put a lot of effort into this or not... It might just die eventually ;)
